export const HACKER_COLORS = {
    background: 'bg-black',
    surface: 'bg-gray-900',
    surfaceLighter: 'bg-gray-800',
    primaryNeon: 'text-green-400',
    primaryNeonHex: '#39FF14',
    primaryNeonGlow: 'shadow-[0_0_15px_rgba(57,255,20,0.5)]',
    secondaryNeon: 'text-cyan-400',
    secondaryNeonHex: '#00FFFF',
    destructiveNeon: 'text-red-500',
    destructiveNeonHex: '#FF1C1C',
    warningNeon: 'text-yellow-400',
    textBase: 'text-slate-300',
    textDim: 'text-slate-500',
    borderNeon: 'border-green-500',
    borderDim: 'border-gray-700',
    buttonPrimaryBg: 'bg-green-500 hover:bg-green-400',
    buttonPrimaryText: 'text-black',
    buttonSecondaryBg: 'bg-cyan-500 hover:bg-cyan-400',
    buttonSecondaryText: 'text-black',
    buttonDestructiveBg: 'bg-red-600 hover:bg-red-500',
    buttonDestructiveText: 'text-white',
};